# Generated by Django 5.0.1 on 2024-03-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_task_created_by_alter_task_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('WorkingOn', 'Workingon'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=200),
        ),
    ]
