# Generated by Django 5.0.1 on 2024-03-19 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0008_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
