# Generated by Django 5.0.1 on 2024-03-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0009_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Working_On', 'Working On'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Planned', max_length=200),
        ),
    ]
